FROM centos

RUN yum update -y \
	&& yum install -y \
		java-1.8.0-openjdk-devel \
		graphviz \
	&& yum clean all 
		

COPY x86_64 /opt/nature

RUN chmod a+x /opt/nature/eclipse	

ENTRYPOINT ["/opt/nature/eclipse"]

EXPOSE 8080